Task_1_1_1
nieroku/syspro_oop pull request #1
Opened 2024-09-03 15:26 UTC by Nikitat0

2024-09-06 16:32 UTC, Sharapov-Maksim requested changes
Посмотрел (пока что всё кроме самого алгоритма), можете начать исправлять замечания и оставлять комментарии.
Когда считаете, что замечание исправлено, напишите в ответ на комментарий об этом

2024-09-06 16:32 UTC, Sharapov-Maksim commented on Task_1_1_1/src/main/java/ru/nikitat0/heapsort/Main.java
> +/** Contains all program function */
GitHub Actions / checkstyle ругается на отсутствие точки в конце

> 7.2 The summary fragment
> ... the fragment is capitalized and punctuated as if it were a complete sentence.
[link](https://google.github.io/styleguide/javaguide.html#s7.2-summary-fragment)

2024-09-06 16:32 UTC, Sharapov-Maksim commented on Task_1_1_1/src/main/java/ru/nikitat0/heapsort/Main.java
> +     * Constructs a binary heap from an array in-place.
javadoc к `heapsort` и `makeHeap` кажется перепутаны

2024-09-06 16:32 UTC, Sharapov-Maksim commented on Task_1_1_1/src/test/java/ru/nikitat0/heapsort/MainTest.java
> +        int[] sample = new int[100];
`100` - неименованная константа, такого следует избегать. Лучше было бы сделать в классе статическую константу:
```
private static final int SAMPLE_ARRAY_SIZE = 100;
```

Но, **в данном случае**, удобнее было бы сделать размер генерируемого массива аргументом функции, тогда разным тестам было бы удобно использовать этот генератор

2024-09-06 16:32 UTC, Sharapov-Maksim commented on Task_1_1_1/src/test/java/ru/nikitat0/heapsort/MainTest.java
> +class MainTest {
> При сдаче задания преподавателю объясните, как выбранный набор тестов обеспечивает корректность вашего алгоритма.

Нужно либо объяснить, почему такого скромного набора тестов достаточно, либо добавить тестов на краевые случаи (например: массив пустой, из одного элемента, ...) и разные входные данные (одинаковые числа, отрицательные/положительные значения, ...)

2024-09-06 16:32 UTC, Sharapov-Maksim commented on Task_1_1_1/src/test/java/ru/nikitat0/heapsort/MainTest.java
> +    void testHeapsort() {
Тесты на вспомогательные функции это правильно. Надо бы только побольше их, на разные сценарии (см. коммент выше)

2024-09-08 11:21 UTC, Nikitat0 commented on Task_1_1_1/src/main/java/ru/nikitat0/heapsort/Main.java
> +/** Contains all program function */
Исправлено

2024-09-08 11:21 UTC, Nikitat0 commented on Task_1_1_1/src/main/java/ru/nikitat0/heapsort/Main.java
> +     * Constructs a binary heap from an array in-place.
Исправлено

2024-09-08 11:22 UTC, Nikitat0 commented on Task_1_1_1/src/test/java/ru/nikitat0/heapsort/MainTest.java
> +        int[] sample = new int[100];
Сделал и то и другое. Параметр для размера может позволить переиспользовать функцию в других местах, а используемую в тестах константу вынес на уровень класса.

2024-09-08 11:33 UTC, Nikitat0 commented on Task_1_1_1/src/test/java/ru/nikitat0/heapsort/MainTest.java
> +class MainTest {
Добавил для обеих функций проверку на то, что они не ломаются при передаче в них пустого массива и тест с массивом с одинаковыми значениями. Тесты на только отрицательные/положительные числа смысла не имеют, потому что функции не используют информацию о том больше нуля число или меньше.

2024-09-08 16:17 UTC, Sharapov-Maksim requested changes

2024-09-08 16:17 UTC, Sharapov-Maksim commented on Task_1_1_1/src/test/java/ru/nikitat0/heapsort/MainTest.java
> +class MainTest {
Массив из одного элемента - тоже вполне краевой случай, надо бы добавить

Аргументировать отсутствие тестов особенностями реализации функции не совсем корректно... Что если реализация изменится? В данном случае ладно, действительно маловероятно, что реализация сортировки начнёт зависеть от знака числа

2024-09-09 01:59 UTC, Nikitat0 commented on Task_1_1_1/src/test/java/ru/nikitat0/heapsort/MainTest.java
> +class MainTest {
Добавил тест с массивом из одного элемента.
Но не совсем понимаю зачем это нужно. Почему мы считаем случай с одним элементом или, например, всеми положительными более краевым, чем `new int[] {2, 23, 26, -1}`? Я бы счёл необходимым добавлять такой тест в ходе реально разработки, только если ранее такая проблема уже возникала, иначе это получается просто "тык пальцем в небо".

2024-09-09 04:00 UTC, Sharapov-Maksim commented on Task_1_1_1/src/test/java/ru/nikitat0/heapsort/MainTest.java
> +class MainTest {
Из одного элемента более краевой, потому что алгоритмы сортировки работают с индексами массива и возможна ситуация, когда пустые массывы обрабатываются корректно, а из одного элемента - нет, а для больших массивов проблемы не возникает.

> Я бы счёл необходимым добавлять такой тест в ходе реально разработки, только если ранее такая проблема уже возникала
Возникала где? У клиента, например? Неприятно будет

Понятно, что сейчас это тренировочное задание, и это может показаться бессмысленным, но в реальной жизни тесты пишут с разной степенью параноидальности, в зависимости от критичности системы. А бывает, что тесты пишут ещё до написания системы - Test-driven development (TDD).

А вот например, [внутренний тест OpenJDK](https://github.com/openjdk/jdk/blob/f0e84b7617aebc421483f36bb7d0b14d0fc39616/test/jdk/java/util/Arrays/Sorting.java#L53), в котором тестируются массивы длинны 1

2024-09-09 04:07 UTC, Sharapov-Maksim commented on Task_1_1_1/src/test/java/ru/nikitat0/heapsort/MainTest.java
> +    void testWithSingletonArray() {
Словом singleton обычно называют шаблон проектирования, неудачное название для теста

2024-09-09 04:10 UTC, Sharapov-Maksim approved these changes
Замечания исправлены

2024-09-09 04:10 UTC, merged

2024-09-09 08:35 UTC, nieroku commented on Task_1_1_1/src/test/java/ru/nikitat0/heapsort/MainTest.java
> +    void testWithSingletonArray() {
Мне кажется из контекста понятно, что имеется ввиду не паттерн, а массив из одного элемента