Task_1_1_2
nieroku/syspro_oop pull request #2
Opened 2024-09-15 07:48 UTC by Nikitat0

2024-09-17 15:38 UTC, Sharapov-Maksim requested changes
Очень хорошая работа, доделывайте. Мягкий дедлайн зачтён

2024-09-17 15:38 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/ru/nikitat0/blackjack/cards/CardView.java
> +public interface CardView {
Вау, первое решение с интерфейсами, круто =)
Расскажите, что такое интерфейс и чем в данном случае он вам помог или чем в целом полезны интерфейсы?

2024-09-20 07:16 UTC, nieroku commented on Task_1_1_2/src/main/java/ru/nikitat0/blackjack/cards/CardView.java
> +public interface CardView {
Интерфейс — это тип данных, определяющий только контракт, представленный набором методов, без какой-либо реализации. Экземпляр интерфейса создать нельзя в силу отсутствия реализации

Конкретно здесь я мог бы использовать sealed classes, чтобы передать ту же идею, что карта может "лежать" либо открытой, либо закрытой, и тогда мы о ней ничего не знаем. Но эта функциональность есть только с версий джавы более старых, чем 11, поэтому я сделал два связанных интерфейса: CardView и CardViewer. CardView — это карта "выложенная на игральный стол", это интерфейс позволяет CardViewer "увидеть" карту и сразу преобразовать в удобный для себя формат

2024-09-22 10:04 UTC, Sharapov-Maksim requested changes
Классно получилось, одну шероховатость заметил только

2024-09-22 10:04 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/ru/nikitat0/blackjack/game/Game.java
> +            new Round().play();
``` 
Task :Main.main()
Добро пожаловать в Блэкджек!
Раунд 1
Дилер раздал карты
    Ваши карты: [Туз Черви (11), Двойка Черви (2)] => 13
    Карты дилера: [Тройка Черви (3), <закрытая карта>]
...
Раунд 2
Дилер раздал карты
    Ваши карты: [Туз Черви (11), Двойка Черви (2)] => 13
    Карты дилера: [Тройка Черви (3), <закрытая карта>]
...
Раунд 3
Дилер раздал карты
    Ваши карты: [Туз Черви (11), Двойка Черви (2)] => 13
    Карты дилера: [Тройка Черви (3), <закрытая карта>]
...
```
![image](https://github.com/user-attachments/assets/9944623e-2987-4be9-9d67-770e5d8fb964)

2024-09-22 13:39 UTC, Nikitat0 commented on Task_1_1_2/src/main/java/ru/nikitat0/blackjack/game/Game.java
> +            new Round().play();
Исправил. После того как сделал рефакторинг не учёл, что колоду надо перемешивать.

2024-09-22 14:36 UTC, Sharapov-Maksim approved these changes
Замечание исправлено

2024-09-22 14:36 UTC, Sharapov-Maksim commented
Задание засчитано, можно мержить

2024-09-22 15:57 UTC, merged