Task_1_1_3
nieroku/syspro_oop pull request #3
Opened 2024-09-22 08:18 UTC by Nikitat0

2024-09-22 13:42 UTC, Nikitat0 commented
Сделаны все дополнительные задания. По поводу code coverage, не совсем понимаю как рассчитывается эта метрика, весь публичный функционал протестирован, как мне кажется.

2024-09-29 05:35 UTC, Sharapov-Maksim commented
Вы можете самостоятельно прогонять тесты с code coverage.
Например, в IDEA:
![image](https://github.com/user-attachments/assets/6b5b683a-8773-454c-af0c-b143be1ee81c)
А потом красным пометятся строчки, которые ни разу не исполнились ни в каком тесте.
![image](https://github.com/user-attachments/assets/45c12c69-86a9-4292-b430-2f46a3d7c0b1)

В вашем случае действительно в публичных методах всё покрыто, но в приватных - не всё. Стоит подобрать такие тестовые сценарии, чтобы приватные методы тоже исполнились и покрылись

2024-09-29 09:05 UTC, Sharapov-Maksim requested changes
Хорошая работа. Мягкий дедлайн зачтён, осталось только тесты чуть доделать, добавить тестовых сценариев для покрытия

2024-09-29 09:05 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nikitat0/expressions/lexer/Lexer.java
> +    private static RuntimeException unexpectedTokenException(
Добавить тест

2024-09-29 09:05 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nikitat0/expressions/lexer/Lexer.java
> +    private static RuntimeException unexpectedCharacterException(char c, int pos) {
Добавить тест

2024-09-30 07:01 UTC, Nikitat0 commented on Task_1_1_3/src/main/java/ru/nikitat0/expressions/lexer/Lexer.java
> +    private static RuntimeException unexpectedCharacterException(char c, int pos) {
Исправлено

2024-09-30 07:01 UTC, Nikitat0 commented on Task_1_1_3/src/main/java/ru/nikitat0/expressions/lexer/Lexer.java
> +    private static RuntimeException unexpectedTokenException(
Исправлено

2024-09-30 07:04 UTC, Nikitat0 commented
> Например, в IDEA:

Специальные инструменты не должны требоваться для прохождения курса

> В вашем случае действительно в публичных методах почти всё покрыто, но в приватных - не всё. Стоит подобрать такие тестовые сценарии, чтобы приватные методы тоже исполнились и покрылись

Добавил тестовые случаи на лексер

2024-09-30 12:22 UTC, Sharapov-Maksim commented
> Специальные инструменты не должны требоваться для прохождения курса

Разумеется, они только рекомендуются =)

2024-09-30 12:27 UTC, Sharapov-Maksim approved these changes
Задание засчитано. Доп. баллы: 2
PR можно мёржить

2024-09-30 15:58 UTC, merged