Task_1_2_1
nieroku/syspro_oop pull request #4
Opened 2024-10-13 03:32 UTC by Nikitat0

2024-10-13 04:14 UTC, Sharapov-Maksim requested changes
Мягкий дедлайн засчитан, доделывайте требуемую функциональность и тесты

2024-10-13 04:14 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/ru/nikitat0/graph/Graph.java
> +    void forEachAdjacent(int u, IntConsumer action);
По заданию нужно ещё метод, возвращающий список всех соседей вершины

2024-10-13 04:14 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/ru/nikitat0/graph/IdentifiersCache.java
> +}
Можно было использовать `Stack<Integer>` из стандартной библиотеки, но я не против вашей реализации, просто к слову

2024-10-13 04:14 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/ru/nikitat0/graph/AdjacencyList.java
> +    }
Заметьте, что `List<E>.add(E e)` принимает элемент и добавляет его в конец списка, а `List.remove(int index)` принимает индекс и удаляет элемент по индексу со сдвигом оставшихся элементов.
В связи с этим, думаю `removeEdge` требует немного другую реализацию, чем сейчас

2024-10-13 04:14 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/ru/nikitat0/graph/AdjacencyList.java
> +        data.get(u).add(v);
`data.get(u)` может вернуть `null`, стоит обработать такую ситуацию, выбросить исключение

2024-10-13 04:14 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/ru/nikitat0/graph/Topsort.java
> +    public static List<Integer> topsort(Graph graph) {
Давайте в javadoc добавим информацию про алгоритм, например название

2024-10-13 16:36 UTC, Nikitat0 commented on Task_1_2_1/src/main/java/ru/nikitat0/graph/Graph.java
> +    void forEachAdjacent(int u, IntConsumer action);
Так вот же он

2024-10-14 07:50 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/ru/nikitat0/graph/Graph.java
> +    void forEachAdjacent(int u, IntConsumer action);
Это метод итерации по вершинам и применения каких-то операций - немного другое

2024-10-17 13:00 UTC, Nikitat0 commented on Task_1_2_1/src/main/java/ru/nikitat0/graph/Graph.java
> +    void forEachAdjacent(int u, IntConsumer action);
Исправлено

2024-10-17 13:00 UTC, nieroku commented on Task_1_2_1/src/main/java/ru/nikitat0/graph/IdentifiersCache.java
> +}
Захотелось свой написать)

2024-10-17 13:00 UTC, nieroku commented on Task_1_2_1/src/main/java/ru/nikitat0/graph/AdjacencyList.java
> +    }
Исправлено

2024-10-17 13:01 UTC, nieroku commented on Task_1_2_1/src/main/java/ru/nikitat0/graph/AdjacencyList.java
> +        data.get(u).add(v);
Исправлено

2024-10-17 13:01 UTC, Nikitat0 commented on Task_1_2_1/src/main/java/ru/nikitat0/graph/Topsort.java
> +    public static List<Integer> topsort(Graph graph) {
Добавил

2024-10-17 13:02 UTC, Nikitat0 commented
Готово полное решение

2024-10-18 17:06 UTC, Sharapov-Maksim requested changes

2024-10-18 17:06 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/ru/nikitat0/graph/Graph.java
> +    }
Протестировать забыли

2024-10-18 17:06 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/ru/nikitat0/graph/Graph.java
> +public interface Graph {
Из задания:
> Не забудьте поддержать операции сравнения на равенство и вывода в строку.

Забыли?

2024-10-20 05:10 UTC, Nikitat0 commented on Task_1_2_1/src/main/java/ru/nikitat0/graph/Graph.java
> +    }
Исправлено

2024-10-20 05:10 UTC, Nikitat0 commented on Task_1_2_1/src/main/java/ru/nikitat0/graph/Graph.java
> +public interface Graph {
Исправлено

2024-10-20 07:08 UTC, Sharapov-Maksim requested changes

2024-10-20 07:08 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/ru/nikitat0/graph/AdjacencyList.java
> +        }
А ведь два графа могут быть равны несмотря на разные представления. Давайте добавим `equals` в интерфейс (где будет описание работы equals) и поддержим сравнение с произвольным `Graph`

2024-10-21 06:23 UTC, Nikitat0 commented on Task_1_2_1/src/main/java/ru/nikitat0/graph/AdjacencyList.java
> +        }
В целом это был вопрос договорённости) Сделал общую реализацию, которая не обращает внимание на конкретный способ хранения графа.

2024-10-21 15:41 UTC, Sharapov-Maksim approved these changes
Задание зачтено, PR можно мёржить

2024-10-21 15:41 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/ru/nikitat0/graph/Graph.java
> +        boolean[] equals = new boolean[] { true };
не понял зачем здесь массив, вроде и просто переменной было бы достаточно

2024-10-22 03:08 UTC, merged

2024-10-22 03:09 UTC, Nikitat0 commented on Task_1_2_1/src/main/java/ru/nikitat0/graph/Graph.java
> +        boolean[] equals = new boolean[] { true };
Джавовские лямбды не умеют захватывать локальные переменные "по ссылке"