Task_1_5_1
nieroku/syspro_oop pull request #5
Opened 2024-12-10 16:33 UTC by Nikitat0

2024-12-11 16:02 UTC, Sharapov-Maksim approved these changes
Мягкий дедлайн зачтён. Когда будете доделывать, не забудьте про javadoc

2024-12-11 16:02 UTC, Sharapov-Maksim commented on Task_1_5_1/src/main/java/ru/nikitat0/mind/Link.java
> +        if (this.getClass() != other.getClass()) {
Проверить `other == null` ещё

2024-12-11 16:02 UTC, Sharapov-Maksim commented on Task_1_5_1/src/main/java/ru/nikitat0/mind/InlineElement.java
> +public abstract class InlineElement {
Не хватает общего корня иерархии элементов, который наверняка пригодится для списков

2024-12-11 16:02 UTC, Sharapov-Maksim commented on Task_1_5_1/src/main/java/ru/nikitat0/mind/OnceIterator.java
> +	}
По контракту `java.util.Iterator#next` надо проверить, есть ли следующий элемент и выбросить `NoSuchElementException`

2024-12-11 16:02 UTC, Sharapov-Maksim commented on Task_1_5_1/src/main/java/ru/nikitat0/mind/InlineElement.java
> +    }
Объясните, почему вы решили использовать сдесь итераторы?

Кажется сейчас можно все использования итератора (в `equals` и `toString`) заменить на рекурсивные вызовы от `text` и `left`. Это бы выглядело не так громоздко и читалось бы лучше

2024-12-11 16:02 UTC, Sharapov-Maksim commented on Task_1_5_1/src/main/java/ru/nikitat0/mind/InlineElement.java
> +    static class Sequence extends InlineElement {
Круто, что вы поддержали последовательности текстовых элементов 👍

2024-12-11 16:09 UTC, Sharapov-Maksim requested changes
Мискликнул по "Approve" =)

2024-12-12 02:30 UTC, Nikitat0 commented on Task_1_5_1/src/main/java/ru/nikitat0/mind/InlineElement.java
> +    }
Одинаковая (семантически) последовательность элементов могла быть построена разными способами
```java
// text1..3 are instances of InlineElement
InlineElement seq1 = text1.join(text2).join(text3);
InlineElement seq2 = text1.join(text2.join(text3));
// seq1.equals(seq2) should be true
```

2024-12-12 02:31 UTC, Nikitat0 commented on Task_1_5_1/src/main/java/ru/nikitat0/mind/Link.java
> +        if (this.getClass() != other.getClass()) {
Это всё-таки входит в контракт `equals()`?

2024-12-12 02:32 UTC, Nikitat0 commented
> не забудьте про javadoc

Можно ли всё-таки не писать `javadoc` на все паблик сущности? Для многих методов и классов название полностью описывает суть

2024-12-12 16:01 UTC, Sharapov-Maksim commented
> > не забудьте про javadoc
> 
> Можно ли всё-таки не писать `javadoc` на все паблик сущности? Для многих методов и классов название полностью описывает суть

Это не мои правила, но они общие для всех, к сожалению =(

> Наличие документации javadoc обязательно.

2024-12-13 15:30 UTC, Sharapov-Maksim commented on Task_1_5_1/src/main/java/ru/nikitat0/mind/Link.java
> +        if (this.getClass() != other.getClass()) {
Из javadoc к `java.lang.Object#equals`
> For any non-null reference value `x`, `x.equals(null)` should return `false`.

Про `NullPointerException` там не написано

2024-12-13 15:33 UTC, Sharapov-Maksim commented on Task_1_5_1/src/main/java/ru/nikitat0/mind/InlineElement.java
> +    }
Хороший поясняющий пример, достойный упоминания в javadoc

2024-12-23 16:51 UTC, Sharapov-Maksim requested changes
\+ тесты и документация

2024-12-23 16:51 UTC, Sharapov-Maksim commented on Task_1_5_1/src/main/java/ru/nikitat0/mind/List.java
> +        }
А нельзя ли сделать только одно поле, с типом `Element`, например? Или сделать общий родительский класс над `Element.Inline` и `Element.Block`. А в `toString` проверять на `instanceof`.

Не должно же быть такого, что `text != null && body != null`? К тому же, упростится API, не придётся передавать лишние аргументы вида `block = null` или `text = null`

2025-01-01 09:35 UTC, merged